### PR TITLE
Update jpegoptim to cedar-14 dependency compatible binary

### PR DESCRIPTION
**Pull request by novazembla**
Hi, 

The jpegoptim binary in the repository does not run on heroku cedar-14 stack as the libjpeg library has changed in the OS. I'm providing here the updated version.

### CODE REVIEW

**Comment by nickcatal** [comment]
@bobbus can you take a look at this/merge it in?

**Comment by bobbus** [comment]
will do this week

**Comment by heythisisnate** [comment]
:+1: appears to work on Cedar-14 on my app

It might be a good idea to do a check here to determine which binary version is appropriate. This will _not_ be backwards compatible with Cedar-10

**Comment by bobbus** [comment]
included in #5

**Pull request merged**
